README.md, base/README.md
=> Changing Ballerina docker base image name

pom.xml, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerExtensionProvider.java, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/exceptions/ArtifactGenerationException.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/DockerModel.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java, src/main/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin, src/test/java/artifactgen/DockerGeneratorTests.java
=> Upgrade ballerina version

README.md, samples/sample4/docker_debug.bal, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/exceptions/DockerPluginException.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/DockerModel.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java, src/test/java/artifactgen/DockerGeneratorTests.java
- Refactor code to support compiler plugin events
- Generates the docker artifacts while compiling without parsing the .balx file.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> Docker for mac
=> Refactor code to support compiler plugin events

.gitignore, README.md, pom.xml, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/DockerModel.java
- Add docker host annotation support
- Fix class loading issue
- Fixes https://github.com/ballerinax/docker/issues/8
=> Add docker host annotation support

src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
=> Fix test case failure

samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal
- Change samples to support new syntax
=> Change samples to support new syntax

base/docker/Dockerfile, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java
- Improve docker error handling
- Change maintainer syntax (Fixes: https://github.com/ballerinax/docker/issues/13)
=> Improve docker error handling

README.md, samples/README.md, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/DockerModel.java
- Add mini-kube support
- Fixes https://github.com/ballerinax/docker/issues/15
=> Add mini-kube support

src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java
=> Fix issue with certpath

README.md, samples/README.md, samples/sample1/README.md, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/README.md, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, src/main/ballerina/ballerinax/docker/annotation.bal
- Change annotations to match new standard
=> Change annotations to match new standard

README.md, samples/sample1/README.md, samples/sample1/hello_world_docker.bal, samples/sample2/README.md, samples/sample3/README.md, samples/sample3/docker_push_sample.bal, samples/sample4/README.md, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/DockerDataHolder.java, src/main/java/org/ballerinax/docker/models/DockerModel.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
- Add docker username and password support from env variables
- Add docker annotation support for endpoint (Fixes https://github.com/ballerinax/docker/issues/20)
=> Improve docker syntaxes

samples/sample3/docker_push_sample.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
- Add env variable support for annotation attributes:
```
@docker:Config {
push:true,
registry:"index.docker.io/$env{DOCKER_USERNAME}",
name:"helloworld-push",
tag:"v2.0.0",
username:"$env{DOCKER_USERNAME}",
password:"$env{DOCKER_PASSWORD}"
}
```
=> Add env variable support

pom.xml
=> Update parent relative path

pom.xml, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, src/main/java/org/ballerinax/docker/DockerExtensionProvider.java
- Changes to support new ballerina syntaxes
=> Changes to support new ballerina syntaxes

pom.xml
> Fix minor typo in artefact id
> Remove spelling mistake
=> fixed minor typo in artifact id

base/README.md, src/main/java/org/ballerinax/docker/models/DockerModel.java, src/test/java/artifactgen/DockerGeneratorTests.java
- Change docker base image version to pom version
=> Change docker base image version

samples/sample1/README.md, samples/sample2/README.md
=> Fix samples

pom.xml, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java
- Remove copyrights from generated Dockerfile (Resolves https://github.com/ballerinax/docker/issues/29)
- Change ballerina version
=> Remove copyrights from generated Dockerfile

README.md, pom.xml, samples/README.md, samples/sample5/README.md, samples/sample5/conf/data.txt, samples/sample5/conf/sample.toml, samples/sample5/hello_config_file.bal, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/handlers/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/models/CopyFileModel.java, src/main/java/org/ballerinax/docker/models/DockerDataHolder.java, src/main/java/org/ballerinax/docker/models/DockerModel.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
- Add @docker:CopyFiles annotation support (Resolves: https://github.com/ballerinax/docker/issues/19)
- Add sample with @docker:CopyFiles annotation
=>  Add @docker:CopyFiles annotation

samples/sample5/README.md, samples/sample5/conf/ballerina.conf, samples/sample5/conf/sample.toml, samples/sample5/hello_config_file.bal
- Modify sample5 to read from config API (Resolves https://github.com/ballerinax/docker/issues/19)
=> Modify sample5 to read from config API

README.md, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal
- Change samples to new ballerina syntax
=> Change samples to new ballerina syntax

README.md, pom.xml, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, spotbugs-exclude.xml, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/test/java/org/ballerinax/docker/handlers/DockerGeneratorTests.java
- Fix failsafe plugin execution phases
- Update annotation to the new syntax
- Update samples to new ballerina syntax
- Add spotbugs-exclude.xml
=>  Update to the new ballerina syntax

pom.xml, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal
=> Update ballerina version

pom.xml, samples/sample1/hello_world_docker.bal, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/models/DockerDataHolder.java
- Add anonymous endpoint support
=> Add anonymous endpoint support

src/main/java/org/ballerinax/docker/DockerPlugin.java
- Add validation to anonymous endpoint
=> Add validation to anonymous endpoint

pom.xml, samples/test_sample.sh, src/main/java/org/ballerinax/docker/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
- Update ballerina version
- Add whitespace check for annotation values
- Add script to test samples
=> Add script to test samples

pom.xml, samples/test_sample.sh
=> Add nexus Repo urls

README.md, pom.xml
- Update ballerina parent version
=> Update ballerina parent version

pom.xml
- Add group id org.ballerainax.docker
=> Add group id

samples/sample5/hello_config_file.bal
=> Update sample to new syntax

README.md, src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java, src/test/java/org/ballerinax/docker/handlers/DockerGeneratorTests.java, src/test/java/org/ballerinax/docker/utils/DockerGenUtilsTest.java, src/test/resources/conf/ballerina.conf, src/test/resources/conf/data.txt
=> Add DockerGenUtils Tests

README.md, pom.xml, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, src/main/java/org/ballerinax/docker/DockerArtifactHandler.java, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java
=> Implement @docker:Expose{}

src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java
=> Fix check-style failure

pom.xml
=> Prepare for next iteration

README.md, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java
- Make endpoints without port to run with default port
- Fix typo in README
=>  Make endpoints without port to run with default port

pom.xml
>  Merge release 0.970.0 beta1
=> Merge release 0.970.0 beta1

pom.xml, samples/sample1/hello_world_docker.bal, src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java
- Read default http listener port from ballerina constants
=> Read default http listener port from ballerina constants

src/main/ballerina/ballerinax/docker/annotation.bal
- Migrate to annotation.bal to new docerina syntax
=> Migrate to annotation.bal to new docerina syntax

src/main/ballerina/ballerinax/docker/annotation.bal
- Remove keywords from doc comments
=> Remove keywords from doc comments

pom.xml
=> Merge release 0.970.0 beta3

pom.xml, src/main/java/org/ballerinax/docker/DockerPlugin.java, src/test/java/org/ballerinax/docker/utils/DockerGenUtilsTest.java
- Update pom.xml to with new ballerina parent
=> Update pom.xml to with new ballerina parent

pom.xml
=> Merge Release 0.970.0 beta4

samples/sample1/hello_world_docker.bal, samples/sample2/README.md, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/test_sample.sh
- Update samples to new syntax
=> Update samples to new syntax

pom.xml
=> Merge release 0.970.0 beta5

src/main/ballerina/ballerinax/docker/annotation.bal
=> Remove package statement

pom.xml
=> Merge release 0.970.0 beta6

pom.xml
=> Release 0.970.0 beta7

pom.xml
=> Release 0.970.0 beta8

pom.xml
=> Release 0.970.0 beta9

pom.xml
=> Release 0.970.0 beta10

pom.xml
=> Release 0.970.0 beta11

pom.xml
=> Release 0.970.0 beta13

pom.xml
=> Release 0.970.0 beta14

pom.xml, samples/sample1/README.md, samples/sample2/README.md, samples/sample3/README.md, samples/sample4/README.md, src/main/ballerina/ballerinax/docker/annotation.bal, src/main/java/org/ballerinax/docker/DockerArtifactHandler.java
- Remove target folder from README
=> Remove target folder from README

pom.xml
=> Release 0.970.0 beta15

pom.xml
=> Release 0.970.0 beta16

src/main/java/org/ballerinax/docker/DockerArtifactHandler.java
- Remove -s option from dockerfile
=> Remove -s option from dockerfile

pom.xml
=> Release 0.970.0 beta17

pom.xml
=> Release 0.970.0 beta18

src/main/java/org/ballerinax/docker/DockerPlugin.java
- Add validation to listener port extraction
=> Add validation to listener port extraction

pom.xml
=> Release 0.970.0 beta19

pom.xml
=> Release 0.970.0 rc1

pom.xml
=> Release 0.970.0

pom.xml
=> Release 0.970.1

pom.xml
=> Release 0.971.0

pom.xml
=> Release 0.972.0

pom.xml
=> Release 0.973.0

assembly/balo.xml, assembly/source.xml, pom.xml, src/main/ballerina/ballerinax/Ballerina.toml
Compile docker package to balo
=> Compile docker package to balo

pom.xml
=> Release 0.974.0

pom.xml, src/main/java/org/ballerinax/docker/DockerPlugin.java
- Update ballerina lang version
- Change supported annotation to support balo.
=> Fix build failures with .balo implementation

pom.xml
=> Release 0.975.0

pom.xml
- Update ballerina-lang version
=> Update ballerina-lang version

src/main/java/org/ballerinax/docker/DockerPlugin.java, src/main/java/org/ballerinax/docker/models/DockerContext.java, src/main/java/org/ballerinax/docker/models/DockerDataHolder.java
- Fix docker artifact generation issue with multi-package
- Depends on https://github.com/ballerina-platform/ballerina-lang/pull/9143
=> Fix artifact generation issue with multi-package

samples/README.md, samples/sample6/.ballerina/.gitignore, samples/sample6/README.md, samples/sample6/burger/burger_api.bal, samples/sample6/pizza/pizza_api.bal, src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java
=> Add multi-package sample 

src/main/ballerina/ballerinax/docker/annotation.bal
- Add record keyword to types
https://github.com/ballerina-platform/ballerina-lang/pull/9216
=> Add record keyword to types

pom.xml
=> Release 0.976.0

src/main/java/org/ballerinax/docker/DockerGenConstants.java, src/main/java/org/ballerinax/docker/DockerPlugin.java
- Update listener endpoint validation logic
=> Update listener endpoint validation logic

pom.xml
=> Release 0.980.0

pom.xml
=> Bump Ballerina version

pom.xml
=> Release 0.980.1

pom.xml
- Update version to project version
=> Update dependency version to project version

docker-extension-test/pom.xml, docker-extension/pom.xml, pom.xml
=> Release 0.981.0

docker-extension-test/pom.xml, docker-extension/pom.xml, pom.xml
=> Release 0.981.1

docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal, samples/sample5/hello_config_file.bal
This PR updates the documentation to the latest format.
=> Update documentation to latest syntax

.gitignore, samples/sample5/hello_config_file.bal
- Update code to latest ballerina/io syntax
=> Update code to latest ballerina/io syntax

docker-extension/src/main/java/org/ballerinax/docker/utils/DockerGenUtils.java
Fixes https://github.com/ballerinax/docker/issues/134
=> Fix checkstyle failure

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension/src/main/java/org/ballerinax/docker/DockerArtifactHandler.java
- Fix option ordering in Dockerfile command
- Resolves https://github.com/ballerinax/docker/issues/138
=> Fix option ordering

samples/README.md, samples/sample6/README.md
> Change terminology from package to module
=> Change terminology from package to module

base/README.md, docker-extension/spotbugs-exclude.xml, docker-extension/src/main/java/org/ballerinax/docker/DockerGenConstants.java, docker-extension/src/main/java/org/ballerinax/docker/models/DockerModel.java
> Refer https://github.com/ballerinax/docker/pull/146.
=> Add ballerina image name to constants. Update documentation.

docker-extension-test/pom.xml
=> Add docker-generator dependency for tests

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/resources/testng.xml, docker-extension/spotbugs-exclude.xml, docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, docker-generator/spotbugs-exclude.xml, pom.xml, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/sample6/burger/burger_api.bal, samples/sample6/pizza/pizza_api.bal
> Syntax update to align with 0.985.0 release
> Upto date syntax with latest ballerina version.
> Update ballerina syntax and updated plugin implementation.
=> Update syntax for 0.985.0 release

README.md, docker-extension-examples/examples/docker-deployment/docker_deployment.bal, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/sample6/burger/burger_api.bal, samples/sample6/pizza/pizza_api.bal
> http:Server was changed to http:Listener.
> Upto date syntax changes.
> Update code.
=> http:Server to http:Listener change

docker-extension-examples/examples/index.js
> Add index.js for BBE site generation.
> For BBE site generation.
> Add index.js
=> Add index.js for BBE examples

samples/sample5/hello_config_file.bal
> Add `match` to `is` changes. 
> Update code to new syntax
> Change `match` statements to `is` statements.
=> Update syntax changes

pom.xml
=> Fix module version in parent pom

docker-extension-examples/examples/docker-deployment/docker_deployment.bal, docker-extension-examples/examples/docker-deployment/docker_deployment.out
=> Update example syntaxes and outputs

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 0.990.0

docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java
> Logging error properly.
> Handle errors
=> Revamp error handling

pom.xml
> Update ballerina snapshot version
=> Release work

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 0.990.1

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 0.990.2

docker-extension-examples/examples/docker-deployment/docker_deployment.description, docker-extension-examples/examples/docker-deployment/docker_deployment.out
Update description and output info of Docker BBE
=> Update description and output info of Docker BBE

docker-extension-test/pom.xml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestException.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension/pom.xml, docker-generator/pom.xml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, pom.xml, samples/sample6/.ballerina/.gitignore
> Change docker client as fabric8 docker client is not maintained anymore
> Use maintained docker client libraries.
=> Change fabric8 docker client to spotify 

docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal
> Update to latest syntax.
> Align with latest syntax
=> Add colon for sealed records

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/ProcessOutput.java, docker-extension-test/src/test/resources/sample-clients/sample1_client.bal, docker-extension-test/src/test/resources/sample-clients/sample2_client.bal, docker-extension-test/src/test/resources/sample-clients/sample5_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_burger_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_pizza_client.bal, docker-extension-test/src/test/resources/sample-clients/sample7_client.bal, docker-extension-test/src/test/resources/testng.xml, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample6/burger/burger_api.bal, samples/sample6/pizza/pizza_api.bal
> Improve tests. Samples are now executed with docker and then tested whether the services are working as expected.
> Test samples are working as expected in service level.
> Starting the ballerina services in docker images generated by the plugin and then test whether the services are responding as expected.
=> Improve test cases to test ballerina services by running them with docker

docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java
> Change binding IP to localhost as test clients are invoking localhost.
=> Change docker instance ip to localhost in tests

docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension-test/src/test/resources/sample-clients/sample1_client.bal, docker-extension-test/src/test/resources/sample-clients/sample2_client.bal, docker-extension-test/src/test/resources/sample-clients/sample5_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_burger_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_pizza_client.bal, docker-extension-test/src/test/resources/sample-clients/sample7_client.bal
> $subject
> Make tests run services.
=> Change docker service tests to 0.0.0.0 host

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java
=> Disable service testing

docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension-test/src/test/resources/sample-clients/sample2_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_burger_client.bal, docker-extension-test/src/test/resources/sample-clients/sample7_client.bal
> Set docker container IP based on OS. Using verifyHostname to connect to secured services.
> Improve tests.
> OS based docker container IP.
=> Set verifyHostname to false and add OS logic

docker-extension-test/pom.xml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension/pom.xml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
> Allowing connecting different docker hosts with docker certs than using default docker host.
> Support for minikube
=> Set docker cert paths in spotify docker client

.codecov.yml, .travis.yml, README.md, docker-extension-coverage-report/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Fix codecov issues

appveyor.yml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension/src/main/java/org/ballerinax/docker/utils/DockerPluginUtils.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java
> Add appveyor to test building in windows.
=> Add appveyor file

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 0.990.3

pom.xml
> Fix building by bumping ballerina version to new snapshot.
> Fix build.
=> Update ballerina dependency to 0.990.4-SNAPSHOT

docker-extension-test/pom.xml, docker-extension/pom.xml, pom.xml
> Use latest versions of the dependencies.
> Use latest versions of the dependencies.
> Update and clean pom files.
=> Bump dependencies to the latest versions

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, docker-extension/src/main/java/org/ballerinax/docker/utils/DockerPluginUtils.java, docker-extension/src/test/java/org/ballerinax/docker/utils/DockerPluginUtilsTest.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java, pom.xml
> Improve error logging.
> Improve logging.
=> Improve error logging for the docker generator.

docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java
> Improves https://github.com/ballerinax/docker/issues/125
=> add validation when copying ballerina conf files

docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension-test/src/test/resources/sample-clients/sample1_client.bal, docker-extension-test/src/test/resources/sample-clients/sample2_client.bal, docker-extension-test/src/test/resources/sample-clients/sample5_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_burger_client.bal, docker-extension-test/src/test/resources/sample-clients/sample6_pizza_client.bal, docker-extension-test/src/test/resources/sample-clients/sample7_client.bal
> Language was modified so that a listener declared globally must be initialized then and there. Due to this reason the tests used in testing the samples has been for broken. This PR fixes the tests.
> Fix tests.
=> Fix tests due to change in language

docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal, samples/sample5/hello_config_file.bal
> Change sealed record syntax.
> Syntax upto date.
=> Add sealed record syntax change

docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal, samples/sample1/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/sample6/burger/burger_api.bal, samples/sample6/pizza/pizza_api.bal, samples/sample7/hello_world_docker.bal
=> Use is statements for responses in samples

pom.xml
> $subject
> Use latest dependencies.
=> bump spotify docker client version

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge release commits

base/README.md, base/docker/DockerfileWindows, docker-extension-test/pom.xml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java
> $subject
> Support windows platform docker images.
=> Windows base image for ballerina

README.md, docker-extension/src/main/ballerina/ballerinax/docker/annotation.bal, docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java
> Preprend registry to the docker images name.
> Fixes and debug loggin.
=> Add docker generator change and logging

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync release branch

docker-extension/pom.xml, pom.xml
> $subject.
> Use latest ballerina core.
=> Update ballerina version to 0.992.0-m2-SNAPSHOT

docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java
> Regression fixes from https://github.com/ballerina-platform/ballerina-lang/pull/15548
> Compilation fixes
=> change BLangArrayLiteral to BLangListConstructorEx

docker-extension-test/pom.xml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/SampleTest.java, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
> $subject.
> Stability
> Use SL4J logging library.
=> Fix logging random logs from libraries.

docker-extension/pom.xml, pom.xml
=> Include stage repository 

docker-extension-test/pom.xml, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension/pom.xml, pom.xml
> Fixes https://github.com/ballerinax/docker/issues/235
=> Fix test cases

docker-extension-balo/src/main/assembly/bin.xml
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/17328
=> Set correct jar and bir locations in bin.xml

docker-extension/pom.xml
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/17329
=> Add missing guava dependency

docker-extension-balo/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.0.0 alpha

docker-extension-balo/scripts/gen-balo.sh, docker-extension-balo/src/main/assembly/bin.xml, pom.xml
=> update gen-balo.sh with new jar name

pom.xml
=> Switch to beta snapshot ballerinalang dependencies

docker-extension-examples/examples/docker-deployment/docker_deployment.out, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
Remove -executable suffix from jar and fix config passing. …
=> Remove -executable from jar and fix config passing

docker-extension/src/main/java/org/ballerinax/docker/utils/DockerPluginUtils.java, samples/sample3/docker_push_sample.bal, samples/test_sample.sh
- Fix resolving environment/system variables for annotations
- Fix sample syntax
=> Fix resolving environment/system variables for annotations

docker-extension-balo/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.0.0

docker-extension-balo/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.0.1

.travis.yml, README.md, appveyor.yml, base/docker/Dockerfile, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample2Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample6Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java
> Update Dockerfile for base image.
=> Update base Dockerfile. Update README.md.

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, pom.xml
> Use a separate user to run the java -jar command.
Fixes https://github.com/ballerinax/docker/issues/287
=> Use a separate user to run the java -jar command.

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, pom.xml
> $subject
Fixes https://github.com/ballerinax/docker/issues/297
=> Fix issue in setting custom image permission

pom.xml
=> Update ballerina version to 1.0.5-SNAPSHOT

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 0.990.6

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java
=> Improve test to check whether user is created

docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java
=> Remove logging password when debug logs are enable

.gitignore, README.md, docker-extension/src/test/java/org/ballerinax/docker/utils/DockerPluginUtilsTest.java, docker-extension/src/test/resources/testng.xml, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java, samples/sample1/README.md, samples/sample2/README.md, samples/sample3/README.md, samples/sample4/README.md, samples/sample5/README.md, samples/sample6/README.md, samples/sample7/README.md
> Fixes https://github.com/ballerinax/docker/issues/293
=> Update readme files for samples

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update project version

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
> Fixes https://github.com/ballerinax/kubernetes/issues/434
=> Fix docker generator step count

docker-extension-annotations/src/main/assembly/bin.xml
=> Modify artifact packing for distribution

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/resources/testng.xml, docker-generator/pom.xml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/CopyFileModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, pom.xml
- Fix debug command
- Resolves https://github.com/ballerinax/docker/issues/317
=> Fix debug command

docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.1.1

.travis.yml, base/README.md, base/base-image/Dockerfile, base/docker/Dockerfile, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java
- Update generated Dockerfile base image
- Resolves https://github.com/ballerinax/docker/issues/335
=> Update generated Dockerfile base image

docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, docker-extension/src/main/java/org/ballerinax/docker/utils/DockerPluginUtils.java
- Update to new Ballerina syntax
=> Update to new Ballerina syntax

README.md, docker-extension-annotations/src/main/ballerina/src/docker/annotation.bal, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample10Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample9Test.java, docker-extension-test/src/test/resources/testng.xml, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, samples/README.md, samples/sample10/README.md, samples/sample10/conf/ballerina.conf, samples/sample10/conf/data.txt, samples/sample10/copy_file_function.bal, samples/sample9/README.md, samples/sample9/hello_world_function.bal
- Implement @docker:CopyFiles and @docker:Config support with main function
- Resolves https://github.com/ballerinax/docker/issues/127 and https://github.com/ballerinax/docker/issues/124
=> Add docker annotations support for main function 

.travis.yml, base/README.md, base/base-image/Dockerfile, base/docker/Dockerfile, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java
- Upgrade base image
- Configure trivy security scan for the base image
=> Upgrade base image

README.md, docker-extension-annotations/src/main/ballerina/src/docker/annotation.bal, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
=> Fix tests for windows due Docker Client change

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge 1.1.2 release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.1.3

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge release-1.1.4 with ballerina-1.1.x

.travis.yml
=> Fix trivy installation

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
=> Fix error handling when pushing images

README.md, samples/sample1/hello_world_docker.bal
=> Update README file with ENV details

.github/workflows/trivy-scan.yml, README.md
=> Remove wget progress bar in trivy scan workflow

.travis.yml, build.gradle, docker-extension-test/build.gradle, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java
=> Enable Jacoco Reports for CodeCov

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync stage with 1.2.x

README.md, docker-extension-annotations/build.gradle
=> Fix incremental build in gradle

docker-extension-test/build.gradle
=> Use Fat Jar to Run Tests

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x branch with the release 1.2.2

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.1.x branch with release 1.1.5

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x branch with release 1.2.2

docker-extension-annotations/build.gradle, docker-extension-test/build.gradle
=> Prepare distribution when running tests

build.gradle, gradle.properties
=> Move project group and version to gradle.properties

docker-extension-examples/examples/docker-deployment/docker_deployment.description
This is to add the How To Guide link in the Docker Deployment BBE. …
=> Add the How To Guide link in the Docker BBE

README.md
- Fix README fields
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/407
=> Fix README fields

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync stage with 1.2.x branch

docker-extension-examples/examples/docker-deployment/docker_deployment.description
Change the How To Deploy Guide link in the BBE. …
=> Change the How To Deploy Guide Link in the BBE

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x with 1.2.3 release

docker-extension-examples/examples/docker-deployment/docker_deployment.description
> Copy of https://github.com/ballerina-platform/module-ballerina-docker/pull/412
=> Change the How To Deploy guide link

docker-extension-annotations/build.gradle, docker-extension-test/build.gradle
> Change the structure of the docker-extension-annotations zip for packing to ballerina distribution.
=> Change docker-extension-annotations output zip

README.md, docker-extension-annotations/build.gradle, docker-extension-annotations/src/docker/annotation.bal, docker-extension/out/production/classes/META-INF/services/org.ballerinalang.spi.SystemPackageRepositoryProvider, docker-extension/out/production/resources/META-INF/services/org.ballerinalang.compiler.plugins.CompilerPlugin, docker-extension/src/main/java/org/ballerinax/docker/DockerAnnotationProcessor.java, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java
- Add docker config file support
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/417
=> Add docker config file support

gradle.properties
=> Remove parallel building in gradle

build.gradle, docker-extension-annotations/build.gradle, docker-extension-test/build.gradle
=> Gradle build improvements

docker-extension-annotations/build.gradle
=> Fix gradle build

docker-extension-annotations/build.gradle
=> Sync release

docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java
=> Fix vscode plugin error

docker-extension-annotations/build.gradle, docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java
=> Sync master

gradle.properties
=> Release 2.0.0 preview1

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/446
=> Fix command args appending logic

docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.bal, docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.description, docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.out, docker-extension-examples/examples/index.js
> Fixes https://github.com/ballerina-platform/module-ballerina-docker/issues/444
=> Add BBE for generating Dockerfile and docker image without annotations

docker-extension-examples/build.gradle, docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.bal
=> Build examples on gradle build command

docker-extension-examples/build.gradle
=> Remove unneccssary work dir for dockker command

docker-extension-examples/build.gradle
=> Disable building examples temporarily

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java
=> Extend the timeout set for running sample5 test

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java
- Disable assertion temporarily
=> Disable assertion temporarily

pom.xml
=> Update Ballerina stage repo path

base/README.md
=> Update readme on building the base images

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync release-1.2.4 and release-1.2.5 branches with ballerina-1.2.x

base/build.gradle, base/thin-jar-base/DockerfileWindows, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java
- Add windows base image support
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/438
=> Add windows base image support

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync ballerina-1.2.x with release-1.2.6

base/build.gradle, docker-extension-test/build.gradle
=> Improve Docker Thin Image Building

docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.description, docker-extension-examples/examples/docker-deployment/docker_deployment.description
Fix the "Deployment Guide" link in the Swan Lake Docker examples. …
=> Fix the "Deployment Guide" Link in the Swan Lake Docker Examples

docker-extension-examples/examples/docker-deployment/docker_deployment.description
Update the "Deployment Guide" link for Docker BBE 1.2.x. …
=> Update the "Deployment Guide" link for Docker BBE 1.2.x

docker-extension-annotations/src/docker/Module.md
Add BBE link in Swan Lake API Docs. …
=> Add BBE Link in Swan Lake API Docs

docker-extension-annotations/src/main/ballerina/src/docker/Module.md
Add BBE link in 1.2.x API Docs.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add BBE Link in 1.2.x API Docs

docker-extension-annotations/src/main/ballerina/src/docker/Module.md
Add the deployment guide link in 1.2.x API Docs. …
=> Add the Deployment Guide Link in 1.2.x API Docs

docker-extension-annotations/src/docker/Module.md
Add the Deployment Guide in Swan Lake API Docs. …
=> Add the Deployment Guide in Swan Lake API Docs

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x branch with 1.2.7 release

docker-extension-annotations/src/docker/Module.md
Update relative paths of Swan Lake API docs. …
=> Update Relative Paths of Swan Lake API Docs

docker-extension-annotations/src/main/ballerina/src/docker/Module.md
Update relative paths of 1.2 API docs. …
=> Update Relative Paths of 1.2 API Docs

docker-extension-annotations/src/docker/annotation.bal
> Fixes broken docker link(65) https://github.com/ballerina-platform/ballerina-lang/issues/24987
=> Update description for FileConfigs annotation

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x branch with 1.2.8 release

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample11Test.java
=> Fix test case

.github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, docker-extension-test/src/test/java/org/ballerinax/docker/test/NoAnnotationsModuleTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/NoAnnotationsTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/NoImageBuildTest.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample10Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample11Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample1Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample4Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample7Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample9Test.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java, samples/sample8/README.md, samples/sample8/cmd_thin_jar.bal
- Update main class name for thinJar execution
- Fix test cases
- Resolves https://github.com/ballerina-platform/ballerina-lang/issues/25951
=> Update main class name for thinJar

README.md
Update documentation for building locally.
Only JDK 8 should be used; https://stackoverflow.com/a/22326989/977957
=> Update documentation 

build.gradle, gradle.properties
$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Introduce separate property for ballerina-lang

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java
- Disable config API test case
=> Disable config API test case

pom.xml
=> Include maven central

.travis.yml
=> Fix trivy scan threat level

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.2.9

.github/workflows/pull-request.yml, base/docker/Dockerfile, docker-extension/src/main/java/org/ballerinax/docker/utils/DockerPluginUtils.java, docker-extension/src/test/java/org/ballerinax/docker/utils/DockerPluginUtilsTest.java
=> Fix build failures

.github/workflows/trivy-scan.yml
=> Fix trivy scan workflow

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.2.10

base/docker/Dockerfile
- Update JAVA_HOME in Dockerfile
=> Update JAVA_HOME in Dockerfile

docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java, docker-extension-test/src/test/resources/testng.xml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
- Add temp RUN instructions to workaround https://github.com/moby/moby/issues/37965.
=> Fix container layers error

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample8Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/utils/DockerTestUtils.java
- Fix intermittent test failure
=> Fix intermittent test failure

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample10Test.java
=> Fix failing tests

docker-generator/build.gradle, gradle/javaProject.gradle
- Publish docker-generator to GitHub packages
=> Publish docker-generator to GitHub packages

.github/workflows/build-master.yml, README.md, docker-extension-annotations/Package.md, docker-extension-examples/examples/docker-deployment/docker_deployment.bal, docker-extension-test/src/test/resources/docker-tests/build_image_false.bal, docker-extension-test/src/test/resources/docker-tests/env.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_listener.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/modules/mix_service/no_annotation.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/modules/mix_service/with_annotation.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/no_annotation_9090.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/no_annotation_9091.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_service.bal, docker-extension-test/src/test/resources/docker-tests/thin_jar/pizza_api.bal, samples/sample1/hello_world_docker.bal, samples/sample11/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/sample6/pizza_api.bal, samples/sample7/hello_world_docker.bal, samples/sample8/cmd_thin_jar.bal
=> Migrate Log API

docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.bal
=> Fix BBE syntax

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
- Update workflow Docker build to workaround https://github.com/moby/moby/issues/37965
=> Resolve workflow build 

docker-extension/src/main/java/org/ballerinax/docker/DockerPlugin.java
=> Add project API changes

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after Release 1.2.11

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after Release 1.2.12

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after release 1.2.13

docker-extension-annotations/build.gradle
> Update ballerina command to bal command
=> Update ballerina command to bal command

README.md, docker-extension-annotations/Package.md, docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.bal, docker-extension-examples/examples/docker-deployment/docker_deployment.bal, docker-extension-test/src/test/resources/docker-tests/build_image_false.bal, docker-extension-test/src/test/resources/docker-tests/env.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_listener.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/modules/mix_service/no_annotation.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/modules/mix_service/with_annotation.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/no_annotation_9090.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_module/no_annotation_9091.bal, docker-extension-test/src/test/resources/docker-tests/no_annotation_service.bal, docker-extension-test/src/test/resources/docker-tests/thin_jar/pizza_api.bal, samples/sample1/hello_world_docker.bal, samples/sample11/hello_world_docker.bal, samples/sample2/hello_world_docker.bal, samples/sample3/docker_push_sample.bal, samples/sample4/docker_debug.bal, samples/sample5/hello_config_file.bal, samples/sample6/pizza_api.bal, samples/sample7/hello_world_docker.bal, samples/sample8/cmd_thin_jar.bal
- Update caller->ok() to caller->respond()
=> Update Ballerina HTTP syntax

docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample10Test.java, docker-extension-test/src/test/java/org/ballerinax/docker/test/samples/Sample5Test.java, docker-extension-test/src/test/resources/sample-clients/sample5_client.bal, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, samples/sample10/README.md, samples/sample10/conf/Config.toml, samples/sample10/conf/ballerina.conf, samples/sample10/copy_file_function.bal, samples/sample5/README.md, samples/sample5/conf/Config.toml, samples/sample5/conf/ballerina.conf, samples/sample5/hello_config_file.bal
=> Migrate config api samples

build.gradle, gradle.properties
=> Remove config dependency

docker-extension-examples/examples/docker-deployment-without-annotations/docker_deployment_without_annotations.description, docker-extension-examples/examples/docker-deployment/docker_deployment.description
Fix broken links in BBEs.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix Broken Links in BBEs

docker-extension-annotations/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

.github/workflows/build-timestamped-master.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
=> Add timestamped version publish configs

.github/workflows/build-master.yml, .github/workflows/build-timestamped-master.yml, .github/workflows/daily-build.yml
=> Update credentials secrets name

.github/workflows/build-timestamped-master.yml
=> Add missing step in timestamped build

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after Release 1.2.14

README.md
=> Standardise master branch build action name

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
- Print ballerina-internal.log on error
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/648
=> Print ballerina-internal.log on error

.github/workflows/build-timestamped-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle
- Improve GitHub action workflow scripts
- ballerina-platform/ballerina-release#547
=> Improve GitHub action workflow scripts

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after Release 1.2.15

pom.xml
=> Update lang dependency to 1.2.16

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x Branch After 1.2.16 Release

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java
- Fix Docker client generation
- Resolves https://github.com/ballerina-platform/module-ballerina-c2c/issues/297
=> Fix Docker client generation

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x Branch After 1.2.17 Release

base/docker/Dockerfile, docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge ballerina-1.2.x into release-stage-1.2.x

base/base-image/Dockerfile, base/docker/Dockerfile
=> Update base Docker image

.github/workflows/trivy-scan.yml, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/DockerGenConstants.java, docker-generator/src/main/java/org/ballerinax/docker/generator/exceptions/DockerGenException.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/utils/DockerGenUtils.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorWindowsTests.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/utils/DockerTestUtils.java, docker-generator/src/test/resources/testng.xml, lombok.config 
=> Remove redundant code

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x Branch After 1.2.18 Release

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorWindowsTests.java
=> Fix main class path

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge ballerina-1.2.x into release-stage-1.2.x 

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x Branch After 1.2.19 Release 

load-tests/ballerina_hello/scripts/run.sh, load-tests/observability_enabled/scripts/run.sh
=> Fix summary path

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x after release 1.2.20

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x after release 1.2.21

base/base-image/Dockerfile, base/docker/Dockerfile
=> Update base image

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with Ballerina 1.2.x

pom.xml
=> Update nexus staging url

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerCMDTest.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
- Sort dependency jar paths
- Resolves https://github.com/ballerina-platform/module-ballerina-c2c/issues/414
=> Sort dependency jar paths

base/base-image/Dockerfile, base/docker/Dockerfile
- Update base image alphine version
- Resolves https://github.com/ballerina-platform/module-ballerina-docker/issues/832
=> Update base image alphine version

.github/workflows/perf-recieve.yml
=> Add perf test receiver workflow

docker-generator/src/main/java/org/ballerinax/docker/generator/models/CopyFileModel.java, docker-generator/src/main/java/org/ballerinax/docker/generator/models/DockerModel.java
=> Replace @Data with @Getter and @Setter for codecov issues

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorNegativeTests.java, docker-generator/src/test/resources/testng.xml
$Subject
Related to ballerina-platform/module-ballerina-c2c#439
Adds negative tests as well - 
Related to #858
> Link to the PR …
=> Fix docker daemon error handling

base/base-image/Dockerfile, base/docker/Dockerfile
=> Bump jre versions

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with Release 1.2.22

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with 1.2.x

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with release 1.2.23

pom.xml
=> Update staging url for 1.2.24 release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Sync 1.2.x after 1.2.24 release

pom.xml
=> Update staging url for 1.2.25 release

.github/workflows/perf-recieve.yml
Updates perf report handler to new format. …
=> Update perf report handler to new format

pom.xml
=> Update commons io version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Merge release 1.2.25 into 1.2.x

base/base-image/Dockerfile, base/docker/Dockerfile
=> Update jre version

base/devcontainer/Dockerfile
=> Update ubuntu tag

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
Fixes ballerina-platform/module-ballerina-c2c#482 …
=> Print ballerina-internal.log only if it exists

pom.xml
=> Update stage URL for 1.2.27 release

docker-generator/src/main/java/org/ballerinax/docker/generator/DockerArtifactHandler.java, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
$Subject. As ballerina-internal.log is not stored anymore. 
Resolves #945
Related to - 
wso2-enterprise/choreo#12124
> Link to …
=> Remove ballerina-internal.log print from Dockerfile CMD

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync ballerina 1.2.x with release 1.2.27

gradle.properties
=> Bump lang version to sl patch 3

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with release 1.2.29

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with Release 1.2.30

base/docker/Dockerfile
=> Add docker cli to dockerfile

pom.xml
This PR upgrades the apache-commons-codec version from 1.12 to 1.15.
Resolves [#135](https://github.com/wso2-enterprise/internal-support-ballerina/issues/135) …
=> Upgrade the apache-commons-codec version to 1.15

base/base-image/Dockerfile, docker-generator/src/test/java/org/ballerinax/docker/generator/test/DockerGeneratorTests.java
$Subject. As latest JREs are not available in alpine package registry. …
=> Update base image Dockerfile

base/docker/Dockerfile
$Subject. This OS level static library is required for JRE to handle HTTP2 + HTTPS cases.
> Link to the PR for changes to the …
=> Add libc6 library to ballerina docker

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with release 1.2.31

pom.xml
=> Update lang url and version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync with release 1.2.32

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x with release 1.2.34

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> [ballerina-1.2.x] Prepare for next development iteration

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync docker `1.2.x` with release `1.2.36`

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.38-stage with 1.2.37-release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `ballerina-1.2.x` with `release-1.2.38`

base/base-image/Dockerfile, base/docker/Dockerfile
=> Update alpine version

pom.xml
Update nexus versions for lang
=> Update nexus versions for lang

pom.xml
=> Update staging url and release version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml
=> Update lang version and release version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update nexus url for 1.2.40-release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update project version with SNAPSHOT

base/docker/Dockerfile
=> Add gcompat library for docker image

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `1.2.x` after `1.2.40` release

base/docker/Dockerfile
$Subject.
Probably due to removed jdk …
=> Bump jre version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `1.2.x` after `1.2.41` release

pom.xml
=> Update nexus url and lang version to 1.2.42

base/docker/Dockerfile
=> Sync Java 17 changes with master

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `1.2.x` after `1.2.42` release

pom.xml
=> Update nexus url and lang version to `1.2.43`

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `ballerina-1.2.x` after  `1.2.43` release

base/docker/Dockerfile
=> Fix a minor typo

base/devcontainer/Dockerfile
=> Bump Ubuntu version

base/devcontainer/Dockerfile
=> Bump base image for devcontainer

base/devcontainer/Dockerfile
=> Update base image for devcontainer

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update nexus urls and release version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `1.2.x` with `release-1.2.47`

pom.xml
=> Update staging URL for 1.2.49 release

pom.xml
=> Sync ballerina-1.2.49-stage with ballerina-1.2.x

pom.xml
=> Sync 1.2.x after 1.2.50 release 

docker-extension-test/pom.xml, docker-extension/pom.xml, pom.xml
- Update docker-java version
- https://github.com/wso2-enterprise/internal-support-ballerina/issues/661
=> Update docker-java version

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync `1.2.x` after `1.2.51` release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Release 1.2.53

pom.xml
- Update Docker java version
- https://github.com/wso2-enterprise/internal-support-ballerina/issues/738
=> Update Docker java version

pom.xml
=> Add woodstox dependency with version

pom.xml
=> [1.2.x] Exclude woodstox transitive dependency

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> [1.2.x] Update snapshot versions

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Add snapshot versions back

pom.xml
=> Change tag

pom.xml
=> Remove woostox dependency related changes

pom.xml
=> Update jersey version and lang URLs

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync after release 1.2.54 

pom.xml
=> Update lang URL for 1.2.55

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update version after 1.2.55 release 

pom.xml
- Fix https://github.com/wso2-enterprise/internal-support-ballerina/issues/871
> Link to the PR for changes to the training …
=> Fix incompatible docker and jersey versions

pom.xml
=> Update lang versions for 1.2.56 release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Update versions after 1.2.56 release

pom.xml
=> Update versions for 1.2.57 release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x after 1.2.57 release

pom.xml
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Update versions for 1.2.58 release

docker-extension-annotations/pom.xml, docker-extension-coverage-report/pom.xml, docker-extension-examples/pom.xml, docker-extension-test/pom.xml, docker-extension/pom.xml, docker-generator/pom.xml, pom.xml
=> Sync 1.2.x after 1.2.58 release
